#:import dp kivy.metrics.dp
#:import TranslationLabel app.widgets.translation_label.TranslationLabel
#:import TranslationButton app.widgets.translation_button.TranslationButton
#:import TranslationTextInput app.widgets.translation_text_input.TranslationTextInput
#:import SafeAreaBoxLayout app.widgets.safe_area.SafeAreaBoxLayout

<AddContactScreen>:
    SafeAreaBoxLayout:
        orientation: "vertical"
        spacing: dp(10)

        TranslationLabel:
            translation_key: "add_contact"
            size_hint_y: None
            height: dp(40)
            font_size: "20sp"

        TranslationTextInput:
            id: contact_name
            hint_translation_key: "contact_name"
            multiline: False
            size_hint_y: None
            height: dp(45)

        TranslationTextInput:
            id: contact_address
            hint_translation_key: "contact_address"
            multiline: False
            size_hint_y: None
            height: dp(45)

        Label:
            id: error_label
            text: ""
            color: 1, 0, 0, 1
            size_hint_y: None
            height: dp(30)

        Widget:

        TranslationButton:
            translation_key: "save"
            size_hint_y: None
            height: dp(50)
            on_release: root.save_contact()

        TranslationButton:
            translation_key: "cancel"
            size_hint_y: None
            height: dp(50)
            on_release: root.cancel()
